version: '3.8'

services:
  web:
    container_name: geolocation_web
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;  python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/usr/src/app/
    links:
      - db:db
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - geonetwork
  db:
    image: postgres:13
    container_name: geolocation_db
    env_file:
      - .env
    volumes:
      - geolocation_data:/var/lib/postgresql/data/
    expose:
      - 5432
    networks:
      - geonetwork
volumes:
  geolocation_data:
networks:
    geonetwork:
        driver: bridge
